CREATE TABLE IF NOT EXISTS properties (
  id text PRIMARY KEY,
  title text NOT NULL,
  location text NOT NULL,
  price numeric NOT NULL,
  type text NOT NULL,
  beds integer NOT NULL,
  baths numeric NOT NULL,
  area numeric NOT NULL,
  "imageUrl" text NOT NULL,
  "imageAlt" text NOT NULL,
  badge text,
  is_featured boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

TRUNCATE TABLE properties;

INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('f1', 'The Glass Pavilion', 'Beverly Hills, California', '5250000', 'SALE', '5', '4.5', '4200', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCra-FKp81t0_OM8bWD55m2o9OOSnR_v7D0UilyExMImxyIcr9tIMZ2Py3HcC0ra_MtSsBkduMcwxUNKI9_iSXFFr_YRON1SF9hNM3fcYy-uG7N7uusL0Z367WINi1V7_GwfNQx-gsbUqLtzVi4ivFyqFQGb4qBs79bALeSFb6i3_ZnJnI1VVrN-VeZYHjfYyQI5C6zy90N3uxWZpwzIBhNoUDKKQjQ8EOEYPoyPTzhnh6b6AS3dkkFJ8t4xSDC6qjhMrQUoUPnAeM', 'Luxury modern villa exterior with pool', 'Exclusive', true);
INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('f2', 'Azure Heights Penthouse', 'Downtown, Vancouver', '3800000', 'SALE', '3', '3', '2100', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDurAGHzg_fpQxFal-obkFVy1Q3WLPdueAQpz0itcQiRV-WfvulnBEDJbNeV8J06q4mX7PTtXYVJjX4-mHVr_khZLZxQ_s8f6fruGqzeqALyMu8wEHRK1EsOs9f4_jPmS7FxcdzrDkR88Wz0GjaPLXkTZRoJQfur59rxYRLi-WYcW-VU_gKS39CPLOMlftvqGvW0IOk5tXgst5mJ4WQM-ICN4vkdel9ido9YFUQga0OI10i6NSe5W4owt33-2YRi_b_ltdZW2QZC5s', 'Modern interior living room with view', 'New Arrival', true);
INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('f3', 'Serene Oasis Estate', 'Malibu, California', '6400000', 'SALE', '6', '6.5', '5500', 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80', 'Luxury Malibu beach villa', 'Exclusive', true);
INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('f4', 'The Obsidian Villa', 'Reykjavik, Iceland', '4100000', 'SALE', '4', '4', '3200', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', 'Modern black Scandinavian villa', 'Design Award', true);
INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('n1', 'Modern Family Home', '123 Pine St, Seattle', '850000', 'SALE', '3', '2', '120', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDuQ9M7U6euA6_cXmYuXnej-N5IuawAW8ds-4G1mzfqmiBc13qXsPhf9_j_zTB8gfEunrBHo8xMsxYwCw_pl8fsxbxRkmyvLR1N9Tiye5ZJG7fwlLn9MwyBanXYhE0emGwp59es1FEyQTRQbmXLUKO74Yj34ZHqrqIkOtMKhP8CmRFvfoHT5LAe10105vUhKNkxIBvtt530nfLigSUTemOOcJMVNmsgactntRJUwOBU_TZzND7BYtDklr8uZcNYlQOK5U74-ufIf-E', 'Modern white house facade', NULL, false);
INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('n2', 'Urban Loft', '456 Elm Ave, Portland', '3200', 'RENT', '1', '1', '85', 'https://lh3.googleusercontent.com/aida-public/AB6AXuB4zNatD3vePhIZAi6OHHJKmamYSgeBNSKjEt32tvkkf4s6aBXCF8R4LNfDfPa9leA0t6N1OKOcP358WwZrnosbCBxSM7EaY2_P7qkx3MinRgmHQn7RvleNTwy8cLigMoR3iv0u83chBVbZYI6BcNMcqv80W-l1pIUgIWZcDIXEqtUatrsojSGfM0lTNDZpkBntBUkRY6NB4ZUymYNYvTHXKbO8NZ6N6uoyuuHqcaRWKzHCNXkOR3p-_EVFAHR8QwijIY_m1mefPZ4', 'Stylish apartment living room', NULL, false);
INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('n3', 'Highland Retreat', '789 Mountain Rd, Bend', '620000', 'SALE', '2', '2', '98', 'https://lh3.googleusercontent.com/aida-public/AB6AXuARQWC19e7mleUpjb8CWLztEv_svJeRFOaC2i-9r9GctFuX5Barzhfai9wNM1WW8bcGlqdFM32d3KPf7SItom5ijdHOz5rGGQPeT7PlWs8-y9LkfcsHLQqsLxalhxP94XJo76_mAMp7T2dVj3hPKHNzTDLLiS6ujSdSsyo3onxQthp4ZkVE8op92gyTLUUucaGaxO8vJvyhH3HuWB07EPqT1WsW0lr9Of5lUPonjG9eiqE1XiJXTqzXUZQt5JorfPwCO1MioZA_Zro', 'Cabin in the woods exterior', NULL, false);
INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('n4', 'Sea View Penthouse', '321 Ocean Dr, Miami', '4500', 'RENT', '3', '3', '180', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBGq4Phm0uDzCnjHAsnWpYTBVpOds_M6iOsJuRQQA5eUZHkztGgtc7eh_OE6wBeyW1-iZh7yyhROnvvmqkAZ9tyAWFGXk0FG52zU4kZ_EDLA0U0cRszy7byNXTeWe0_hS53SYmtCTEV8Y1AM-WxiIC38UMa15QwFDjXtCGQOxoh35K0Ol_70vfsxm0VqDbaWkr8tcEbLTLy0NXH_GcpGK4lAXizgxYOIlFWGyau-4OIfPZRpjCBDbz_qu3VlN201UUJGiuM9ajVd-U', 'Bright bedroom with large window', NULL, false);
INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('n5', 'Central Studio', '555 Main St, Chicago', '550000', 'SALE', '1', '1', '50', 'https://lh3.googleusercontent.com/aida-public/AB6AXuA1w-Hb1289NqZKon3VK8bpmMiCDYYiAMT5egzTINo9m9wSZRHv-k-1IGTVoL1NT8YeZXJHa87JPNDIPrtrbP7jChHq0ypXF90uByhC6VA9O788_B4FY8JVg4chbWN9bcrn9-9FvVvfZX8Aj60Iqg_C8CsCA9DEnJqi2rJvzmK5UP5z-9XRTRjBneAPCa8iGgGWBD9yYKsziN6vn0ePBDGo3inieQtmbr46W31p6UfQ649XRxTm7ygOY2J-jxW1r0qWs8i97KGpkTE', 'Cozy apartment interior', NULL, false);
INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('n6', 'Garden Villa', '999 Oak Ln, Austin', '2800', 'RENT', '2', '2', '110', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCfGXdY0g51ojSg0GMeTW9ndLY3mpKK3oMtWxo2nwd_dwi1pgn1Boi_ovaDGIFhUA7nwu3WdBch8ZuHxoHu3QfgM5ceAsp8pglRVyCROWNcy9zeDNP2wqLoevyKGcaEyFYHYpIx2KK46nLWthnHiHugmkKw48kJsL8IjMO1bL3T1Zwt8bvQDTTUHTgB3GqZ2RU2asRzF1jVg0rLw3LWXXTq0YF1CsbhlWpYOuCEpH5bB8zkBlbKXR4At_M46AL8rJqn5c6BrPD5PP8', 'Modern minimalist home exterior', NULL, false);
INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('n7', 'Scandinavian Cabin', 'Oslo, Norway', '1200000', 'SALE', '2', '1.5', '105', 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=80', 'Wood cabin in snowy landscape', NULL, false);
INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('n8', 'Mid-Century Residence', 'Palm Springs, California', '1850000', 'SALE', '4', '3', '220', 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80', 'Mid-century modern house with pool', NULL, false);
INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('n9', 'Industrial Loft Studio', 'Brooklyn, New York', '4200', 'RENT', '1', '1', '78', 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80', 'Brooklyn brick loft interior', NULL, false);
INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('n10', 'Contemporary Lake House', 'Lake Tahoe, Nevada', '2900000', 'SALE', '4', '4.5', '310', 'https://images.unsplash.com/photo-1502005229762-fc1b2b812ca5?auto=format&fit=crop&w=800&q=80', 'Lakefront villa with deck', NULL, false);
INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('n11', 'Boho Chic Apartment', 'Ibiza, Spain', '3500', 'RENT', '2', '2', '90', 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80', 'Ibiza apartment balcony view', NULL, false);
INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('n12', 'Kyoto Townhouse', 'Kyoto, Japan', '950000', 'SALE', '3', '2', '135', 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80', 'Traditional Japanese townhouse interior', NULL, false);
INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('n13', 'Skyline Penthouse Suite', 'Singapore', '8500', 'RENT', '2', '2.5', '140', 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80', 'Stunning penthouse bedroom with glass walls', NULL, false);
INSERT INTO properties (id, title, location, price, type, beds, baths, area, "imageUrl", "imageAlt", badge, is_featured) VALUES ('n14', 'Tuscan Stone Villa', 'Florence, Italy', '3400000', 'SALE', '5', '5', '450', 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80', 'Rustic Italian villa facade', NULL, false);
